"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./debrief.module.css";

export default function DebriefStream({ runId, initialContent }) {
  const router = useRouter();
  // If a complete debrief was already in the DB, render it directly.
  const [content, setContent] = useState(initialContent || "");
  const [status, setStatus] = useState(initialContent ? "complete" : "idle");
  const [error, setError] = useState("");
  const startedRef = useRef(false);

  useEffect(() => {
    if (initialContent) return; // already complete
    if (startedRef.current) return; // strict-mode double-fire guard
    startedRef.current = true;
    startStream();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  async function startStream() {
    setStatus("streaming");
    setError("");
    setContent("");

    try {
      const res = await fetch(`/api/runs/${runId}/debrief`, { method: "POST" });
      if (!res.ok || !res.body) {
        const text = await res.text().catch(() => "");
        throw new Error(text || `Failed (${res.status})`);
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        setContent((prev) => prev + chunk);
      }

      setStatus("complete");
      router.refresh(); // bust router cache so dashboard shows "View debrief" on back navigation
    } catch (err) {
      console.error(err);
      setError(err.message || "Couldn't generate the debrief.");
      setStatus("error");
    }
  }

  return (
    <div className={styles.debriefContainer}>
      {status === "idle" && (
        <div className={styles.starting}>Starting the debrief…</div>
      )}

      {status === "streaming" && content === "" && (
        <div className={styles.thinking}>
          <span className={styles.thinkingDot} />
          <span className={styles.thinkingDot} />
          <span className={styles.thinkingDot} />
          <span className={styles.thinkingLabel}>Reading the run</span>
        </div>
      )}

      {content && (
        <div className={styles.debrief}>
          <DebriefBody text={content} />
          {status === "streaming" && <span className={styles.cursor} />}
        </div>
      )}

      {status === "error" && (
        <div className={styles.errorBox}>
          <div className={styles.errorLabel}>Couldn't generate debrief</div>
          <div className={styles.errorMsg}>{error}</div>
          <button onClick={() => { startedRef.current = false; startStream(); }} className={styles.retryBtn}>
            Try again
          </button>
        </div>
      )}

      {status === "complete" && (
        <div className={styles.footer}>
          <span>Generated by your AI coach · v4.1</span>
        </div>
      )}
    </div>
  );
}

/**
 * Minimal markdown renderer for the debrief format:
 *  - **THE DEBRIEF** and **THE WEEK AHEAD** headers
 *  - Paragraphs separated by blank lines
 *  - Inline **bold**
 *
 * Hand-rolled because pulling in a markdown lib for two patterns is overkill.
 */
function DebriefBody({ text }) {
  const blocks = text.split(/\n\s*\n/).filter(Boolean);

  return (
    <>
      {blocks.map((block, i) => {
        const trimmed = block.trim();

        // Headers — lines that are entirely **bold** like "**THE DEBRIEF**"
        const headerMatch = trimmed.match(/^\*\*(.+?)\*\*$/);
        if (headerMatch) {
          return (
            <h2 key={i} className={styles.sectionHeader}>
              {headerMatch[1]}
            </h2>
          );
        }

        // Bullet list — block contains lines starting with "- "
        const lines = trimmed.split("\n");
        if (lines.some(l => l.trimStart().startsWith("- "))) {
          return (
            <ul key={i} className={styles.bulletList}>
              {lines.filter(l => l.trim()).map((line, j) => (
                <li key={j} className={styles.bulletItem}>
                  {renderInline(line.replace(/^\s*-\s*/, ""))}
                </li>
              ))}
            </ul>
          );
        }

        // Paragraph with potential inline **bold**
        return (
          <p key={i} className={styles.paragraph}>
            {renderInline(trimmed)}
          </p>
        );
      })}
    </>
  );
}

function renderInline(text) {
  const parts = text.split(/(\*\*[^*]+\*\*)/);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return <strong key={i}>{part.slice(2, -2)}</strong>;
    }
    return <span key={i}>{part}</span>;
  });
}
